// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	types "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/types"
)

// EVPNCNCConfigApplyConfiguration represents a declarative configuration of the EVPNCNCConfig type for use
// with apply.
//
// EVPNCNCConfig configures the parent VRF created by a CNC to connect EVPN-based CUDNs.
// The parent VRF acts as the L3 routing hub: it owns a single L3 VNI and imports routes
// from each connected CUDN's per-CUDN VRF via FRR's `import vrf` directive.
type EVPNCNCConfigApplyConfiguration struct {
	// ipVRF configures the parent VRF's L3 VNI and optional route target.
	// The VNI must be unique across all EVPN VNIs in the cluster (both CUDN VNIs and
	// other CNC parent VRF VNIs). If routeTarget is not specified, it is auto-generated
	// as "<ASN>:<VNI>".
	IPVRF *types.VRFConfig `json:"ipVRF,omitempty"`
}

// EVPNCNCConfigApplyConfiguration constructs a declarative configuration of the EVPNCNCConfig type for use with
// apply.
func EVPNCNCConfig() *EVPNCNCConfigApplyConfiguration {
	return &EVPNCNCConfigApplyConfiguration{}
}

// WithIPVRF sets the IPVRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPVRF field is set to the value of the last call.
func (b *EVPNCNCConfigApplyConfiguration) WithIPVRF(value types.VRFConfig) *EVPNCNCConfigApplyConfiguration {
	b.IPVRF = &value
	return b
}
