/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AvailabilityZoneApplyConfiguration represents a declarative configuration of the AvailabilityZone type for use
// with apply.
//
// AvailabilityZone pins workloads to specific nodes or clusters.
type AvailabilityZoneApplyConfiguration struct {
	// ClusterSelector selects the target cluster(s) for multi-cluster deployments.
	ClusterSelector *v1.LabelSelectorApplyConfiguration `json:"clusterSelector,omitempty"`
	// NodeSelector restricts the subnet's pods to nodes matching these labels.
	// When set, the controller annotates the namespace with openshift.io/node-selector.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
}

// AvailabilityZoneApplyConfiguration constructs a declarative configuration of the AvailabilityZone type for use with
// apply.
func AvailabilityZone() *AvailabilityZoneApplyConfiguration {
	return &AvailabilityZoneApplyConfiguration{}
}

// WithClusterSelector sets the ClusterSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterSelector field is set to the value of the last call.
func (b *AvailabilityZoneApplyConfiguration) WithClusterSelector(value *v1.LabelSelectorApplyConfiguration) *AvailabilityZoneApplyConfiguration {
	b.ClusterSelector = value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *AvailabilityZoneApplyConfiguration) WithNodeSelector(entries map[string]string) *AvailabilityZoneApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
