/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	vpcv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/vpc/v1beta1"
)

// VPCSubnetApplyConfiguration represents a declarative configuration of the VPCSubnet type for use
// with apply.
//
// VPCSubnet describes a single subnet within a VPC.
type VPCSubnetApplyConfiguration struct {
	// Name is the subnet identifier, unique within the VPC.
	// The resulting Namespace and UDN are named "<vpc-name>-<subnet-name>".
	Name *string `json:"name,omitempty"`
	// CIDRs are the IP ranges for this subnet.
	CIDRs []vpcv1beta1.CIDR `json:"cidrs,omitempty"`
	// Type is the connectivity type. Defaults to Private.
	Type *vpcv1beta1.SubnetType `json:"type,omitempty"`
	// AvailabilityZone optionally pins pods to specific nodes/clusters.
	AvailabilityZone *AvailabilityZoneApplyConfiguration `json:"availabilityZone,omitempty"`
}

// VPCSubnetApplyConfiguration constructs a declarative configuration of the VPCSubnet type for use with
// apply.
func VPCSubnet() *VPCSubnetApplyConfiguration {
	return &VPCSubnetApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VPCSubnetApplyConfiguration) WithName(value string) *VPCSubnetApplyConfiguration {
	b.Name = &value
	return b
}

// WithCIDRs adds the given value to the CIDRs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CIDRs field.
func (b *VPCSubnetApplyConfiguration) WithCIDRs(values ...vpcv1beta1.CIDR) *VPCSubnetApplyConfiguration {
	for i := range values {
		b.CIDRs = append(b.CIDRs, values[i])
	}
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VPCSubnetApplyConfiguration) WithType(value vpcv1beta1.SubnetType) *VPCSubnetApplyConfiguration {
	b.Type = &value
	return b
}

// WithAvailabilityZone sets the AvailabilityZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailabilityZone field is set to the value of the last call.
func (b *VPCSubnetApplyConfiguration) WithAvailabilityZone(value *AvailabilityZoneApplyConfiguration) *VPCSubnetApplyConfiguration {
	b.AvailabilityZone = value
	return b
}
