/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// VPCSpecApplyConfiguration represents a declarative configuration of the VPCSpec type for use
// with apply.
//
// VPCSpec defines the desired state of a VPC.
type VPCSpecApplyConfiguration struct {
	// Subnets is the list of subnets within this VPC.
	// Each subnet maps 1:1 to a Namespace + UserDefinedNetwork (L2 EVPN).
	Subnets []VPCSubnetApplyConfiguration `json:"subnets,omitempty"`
}

// VPCSpecApplyConfiguration constructs a declarative configuration of the VPCSpec type for use with
// apply.
func VPCSpec() *VPCSpecApplyConfiguration {
	return &VPCSpecApplyConfiguration{}
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *VPCSpecApplyConfiguration) WithSubnets(values ...*VPCSubnetApplyConfiguration) *VPCSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubnets")
		}
		b.Subnets = append(b.Subnets, *values[i])
	}
	return b
}
